# Generated by Django 2.0.4 on 2018-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180423_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='passing_grade',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='Default Title', max_length=70),
        ),
        migrations.AddField(
            model_name='surveypage',
            name='page_order',
            field=models.IntegerField(null=True),
        ),
    ]
