# Generated by Django 2.0.4 on 2018-04-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180424_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveypage',
            old_name='page_order',
            new_name='page_nr',
        ),
    ]
